[database]
host = "localhost"
user = "postgres"
password = "postgres"
database = "PhishingSite"

[feeds]
usom_feed = "https://www.usom.gov.tr/url-list.txt"
urlhaus_feed = "https://urlhaus.abuse.ch/downloads/text_online/"
alienvault_vetted = "https://otx.alienvault.com/otxapi/pulses/60a794fa6de6293139323f21/indicators/?sort=-created&limit=10000&page=1"
alienvault_turkey = "https://otx.alienvault.com/otxapi/pulses/64b13f10dd3a7cdbcecd89b7/indicators/?sort=-created&limit=1000&page=1"
alienvault_domain = "https://otx.alienvault.com/otxapi/pulses/64b13f10dd3a7cdbcecd89b7/indicators/?sort=-created&limit=1000&page=1"
alienvault_url = "https://otx.alienvault.com/otxapi/pulses/5e98271289d56c79998870d9/indicators/?sort=-created&limit=10000&page=1"
tweet_feed = "https://raw.githubusercontent.com/0xDanielLopez/TweetFeed/master/year.csv"
phishtank_feed = "https://data.phishtank.com/data/online-valid.csv"


[version]
value = "3"

[services.app]
[ports.app]
app = 8000

[services.app.environment.app]
DB_HOST = "db"
DB_USER = "postgres"
DB_PASSWORD = "postgres"
DB_NAME = "PhishingSite"

[services.db.environment.db]
POSTGRES_USER = "postgres"
POSTGRES_PASSWORD = "postgres"
POSTGRES_DB = "PhishingSite"
