version: '${version.value}'
services:
  app:
    ports:
      - '${services.app.ports.app}:${services.app.ports.app}'
    environment:
      - DB_HOST=${services.app.environment.app.DB_HOST}
      - DB_USER=${services.app.environment.app.DB_USER}
      - DB_PASSWORD=${services.app.environment.app.DB_PASSWORD}
      - DB_NAME=${services.app.environment.app.DB_NAME}
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=${services.db.environment.db.POSTGRES_USER}
      - POSTGRES_PASSWORD=${services.db.environment.db.POSTGRES_PASSWORD}
      - POSTGRES_DB=${services.db.environment.db.POSTGRES_DB}
